### ISSUE TITLE
another suggestion for multiple workers issue

### ISSUE THREAD

**Issue by mrpn** [breqdev/flask-discord-interactions#123]
thanks for this extension! it's super easy to use within Flask! 

I'm not an expert, but I use the following command to register commands. would this be something useful for the documentation? 
```
from flask import Flask
from flask_discord_interactions import DiscordInteractions
from dotenv import load_dotenv

app = Flask(__name__)
discord = DiscordInteractions(app)

@app.before_first_request
def register_commands():
    print("registering commands!")
    discord.update_commands(guild_id=os.environ.get("GUILD_ID"))
```

**Comment by breqdev** [comment]
Thanks for the suggestion! The method you mention is a lot cleaner than the previous approach, but it does seem to be deprecated according to the [Flask docs](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.before_first_request). As such, I'm hesitant to include it in the library's documentation. Thanks again though, and I'm glad you find this library useful!
