### ISSUE TITLE
Feature request/question: How do we signal an error from a command?

### ISSUE THREAD

**Issue by ali1234** [breqdev/flask-discord-interactions#124]
Example:

```
@discord.command()
def hextodec(ctx, value: str):
    try:
        return str(int(value, 16))
    except ValueError:
        raise # ???
```

Just allowing the exception to continue results in this:

![image](https://user-images.githubusercontent.com/651970/219133450-abd267ba-f8e9-4f0c-8b74-e5010b829bbf.png)

I would like to be able to supply a custom error message here while keeping the result visible only to the calling user. Is this possible? I couldn't find anything in the docs about it.

**Comment by ali1234** [comment]
It seems like one possible way to do it is something like this:

```
    except ValueError as e:
        return Message(content=str(e), ephemeral=True)
```
That gets you this:

![image](https://user-images.githubusercontent.com/651970/219135299-f7b87813-4423-4fed-8576-dee1fc40bd84.png)

No warning, but it is close.

Anyway it would be nice if there was a section in the docs about this.

**Comment by breqdev** [comment]
As far as I'm aware, that red error message is hardcoded in Discord and not something that you can override. As you've found, using an ephemeral message is often a useful alternative. I've added a short mention of this technique to the docs.

**Comment by ali1234** [comment]
Thanks. I came up with this for error handling:

```python3
def ErrorMessage(ctx, e, title=None):
    message = Message(
        embed = Embed(
            title=str(e) or title,
            color=0xff0000,
        ),
        ephemeral=True
    )
    if ctx.author.id == "<your user ID>":
        import traceback
        message.embed.description = f'```{traceback.format_exc()}```'
    return message
```

I use it like this:

```python3
    try:
        ...
        try:
            x = do_foo()
        except Exception as e:
            raise MyException("Error while doing foo.") from e
        ...

    except MyException as e:
        return ErrorMessage(ctx, e)

    except Exception as e:
        return ErrorMessage(ctx, e, "Generic error message for everything else.")
```

Now users will only see the custom error messages, but the full traceback is still available to me - including the real original exception.
